# Cross-compile changes by Thomas E. Hansen (CodingCellist) 2021-03-08
LOCK_LIB_PATH := /home/gesalous/Splash-3/deps/lib
LOCK_INCLUDE_PATH := /home/gesalous/Splash-3/deps/include
CC := $(TOOLCHAIN_PREFIX)gcc
CFLAGS := -O2 -pthread -D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=200112 -std=c11 -g -fno-strict-aliasing
# LDFLAGS := -lm

# Add these lines to your existing Makefile.config
CFLAGS += -I$(LOCK_INCLUDE_PATH)
LDFLAGS := -lm -L$(LOCK_LIB_PATH) -Wl,-rpath,$(LOCK_LIB_PATH) -lges_locks
# BASEDIR needs to be set to the same directory as this Makefile
# BASEDIR := $(HOME)/Splash-3/codes
BASEDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
# MACROS := $(BASEDIR)/pthread_macros/pthread.m4.stougie
MACROS := $(BASEDIR)/ges_macros/pthread.m4.stougie
M4 := m4 -Ulen -Uindex

ifndef BASEDIR
$(error Please define the BASEDIR variable)
endif

x = *

$(TARGET): $(OBJS) $(EXTRADEPS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET)

%.h: %.h.in
	$(M4) $(MACROS) $< > $@

%.c: %.c.in
	$(M4) $(MACROS) $< > $@

%.o: %.c $(EXTRADEPS)
	$(CC) -c $(CFLAGS) $<
